---
- name: Clone yay
  tags:
    - aur
    - packages
    - light-install
    - full-install
  ansible.builtin.git:
    version: master
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "{{ ansible_env.HOME }}/.config/yay"
    update: true
  when: ansible_distribution == "Archlinux"

- name: Create the `aur_builder` user
  tags:
    - aur
    - packages
    - light-install
    - full-install
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel
  become: true
  when: ansible_distribution == "Archlinux"

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  tags:
    - aur
    - packages
    - light-install
    - full-install
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    validate: 'visudo -cf %s'
    mode: 0440
  become: true
  when: ansible_distribution == "Archlinux"

- name: Build and install yay
  tags:
    - aur
    - packages
    - light-install
    - full-install
  ansible.builtin.command:
    chdir: "{{ ansible_env.HOME }}/.config/yay"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay
  when: ansible_distribution == "Archlinux"
