---
- name: Install gcc, libxft-dev, libxinerama-dev (dwm dependency)
  tags:
    - full-install
    - light-install
    - dwm
  ansible.builtin.package:
    name:
      - gcc
      - libxft-dev
      - libxinerama-dev
    state: present
    update_cache: true
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Clone dwm
  tags:
    - full-install
    - light-install
    - dwm
  ansible.builtin.git:
    version: main
    repo: git@github.com:andre-gonzalez/dwm.git
    dest: "{{ ansible_env.HOME }}/.config/dwm"
    accept_hostkey: true
  ignore_errors: true

- name: Install dwm
  tags:
    - full-install
    - light-install
    - dwm
  community.general.make:
    chdir: "{{ ansible_env.HOME }}/.config/dwm"
    target: install
  become: true
