---
- name: copy file vconsole.conf
  tags:
    - full-install
    - light-install
    - keyboard
  ansible.builtin.copy:
    src: vconsole.conf
    dest: /etc
    owner: root
    group: root
    mode: 0644
  become: true
