---
- name: Install python libs
  tags:
    - full-install
    - light-install
    - python
  ansible.builtin.pip:
    name:
      - pandas # Datascience Dataframes
      - numpy # Datascience
      - scrapy # Webscraping
      - bs4 # Beautiful Soup - Webscraping
      - apache-airflow # Data pipelines orchestration
      - awscli # Aws cli interface
      - jupyter # Jupyter notebooks
      - requests # API calls
      - SQLAlchemy # Database connect utiliy
      - ipdb # Debug python code
      - psycopg2-binary # Postgresql database adapter
      - mysql-connector-python # Mysql database adapter
      - virtualenv # Python virtual environments
      - mysqlclient
      - pyspark
      - virtualenv
    state: present

- name: Install python virtualenv as root so ansible can use it
  tags:
    - full-install
    - light-install
    - python
  ansible.builtin.pip:
    name:
      - virtualenv # Python virtual environments
    state: present
  become: true
  become_user: root
