---
- name: Install aur packages
  tags:
    - aur
    - packages
    - light-install
    - full-install
  kewlfft.aur.aur:
    name:
      - obsidian
      - xflux
      - slack-desktop
      - spotify
      - insync
      - dashbinsh
      - htim
      - tmux-bash-completion-git
      - whatsapp-nativefier
      - mysql
    use: yay
    state: present
    update_cache: true
  when: ansible_distribution == "Archlinux"
  ignore_errors: true

- name: Install informant
  tags:
    - aur
    - light-install
    - packages
    - full-install
  kewlfft.aur.aur:
    name:
      - informant
    use: yay
    state: present
    update_cache: false
  when: ansible_distribution == "Archlinux"
  ignore_errors: true
  notify: Mark all informant news as read

