---
- name: Ensure aws directory exists in .config
  tags:
    - full-install
    - light-install
    - aws
  ansible.builtin.file:
    dest: "{{ ansible_env.HOME }}/.config/aws"
    mode: 0700
    state: directory

- name: copy credentials and config files
  tags:
    - full-install
    - light-install
    - aws
  ansible.builtin.copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'credentials-aws', dest: '{{ ansible_env.HOME }}/.config/aws/credentials', mode: 0600 }
    - { src: 'config-aws', dest: '{{ ansible_env.HOME }}/.config/aws/config', mode: 0600 }
