---
- name: required libraries for brave in Ubuntu
  tags:
    - aur
    - brave
    - never
  ansible.builtin.package:
    name: ["curl", "apt-transport-https"]
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Brave Browser archive-keyring.gpg download in Ubuntu
  tags:
    - aur
    - brave
    - never
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Brave Browser PPA setting in Ubuntu
  tags:
    - aur
    - never
    - brave
  ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] >
    https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Brave Browser apt installation in Ubuntu
  tags:
    - aur
    - never
    - brave
  ansible.builtin.package:
    name: brave-browser
    update_cache: true
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Install brave via aur package
  tags:
    - aur
    - never
    - brave
  kewlfft.aur.aur:
    name:
      - brave-bin
    use: yay
    state: present
    update_cache: true
  when: ansible_distribution == "Archlinux"
  ignore_errors: true
