---
- name: Set python_pip variable when distribution is Archlinux (if necessary)
  tags:
    - full-install
    - light-install
    - packages
    - collections-install
  ansible.builtin.set_fact:
    python_pip: python-pip
  when: ansible_distribution == "Archlinux"

- name: Set python_pip variable when distribution is Ubuntu (if necessary)
  tags:
    - full-install
    - light-install
    - packages
    - collections-install
  ansible.builtin.set_fact:
    python_pip: pipenv
  when: ansible_distribution == "Ubuntu"

- name: install ansible-galaxy collections install package dependencies
  tags:
    - full-install
    - light-install
    - collections-install
  ansible.builtin.package:
    name:
      - "{{ python_pip }}"
    state: present
    update_cache: true
  become: true

- name: Install collection kewlfft.aur
  tags:
    - aur
    - never
    - collections-install
  community.general.ansible_galaxy_install:
    type: collection
    name: kewlfft.aur

- name: Install collection community.general (for ufw)
  tags:
    - full-install
    - light-install
    - ufw
  community.general.ansible_galaxy_install:
    type: collection
    name: community.general
