---
- name: install cron job (ansible-pull)
  tags:
    - full-install
    - light-install
    - cron
  ansible.builtin.cron:
    user: ansible
    name: "ansible provision"
    minute: "*/10"
    disabled: true
    job: "/usr/bin/ansible-pull --vault-password-file {{ ansible_env.HOME }}/.vault_key -o -U https://github.com/andre-gonzalez/ansible-pull.git \
          2>> {{ ansible_env.HOME }}/ansible-pull-error-logs.txt \
          1>> {{ ansible_env.HOME }}/gdrive-pessoal/pessoal/programação/cron-logs/stdout-logs/ansible-pull-stdout-logs.txt"
  become: true

- name: install cron job (profile-selector)
  tags:
    - full-install
    - light-install
    - cron
  ansible.builtin.cron:
    user: "{{ ansible_env.USER }}"
    name: "profile-selector"
    special_time: reboot
    disabled: false
    job: "DISPLAY=:0 {{ ansible_env.HOME }}/.scripts/profile-selector"
  become: true

- name: install cron job (remove downloads folder)
  tags:
    - full-install
    - light-install
    - cron
  ansible.builtin.cron:
    user: "{{ ansible_env.USER }}"
    name: "remove-downloads-folder-reboot"
    special_time: reboot
    disabled: false
    job: "sleep 60 && rm -r {{ ansible_env.HOME }}/Downloads"

- name: install cron job (remove downloads folder)
  tags:
    - full-install
    - light-install
    - cron
  ansible.builtin.cron:
    user: "{{ ansible_env.USER }}"
    name: "remove-downloads-folder"
    minute: "*/10"
    disabled: false
    job: "rm -r {{ ansible_env.HOME }}/Downloads"

- name: install cron job (update fish_history)
  tags:
    - full-install
    - light-install
    - cron
    - fish
  ansible.builtin.cron:
    user: "{{ ansible_env.USER }}"
    name: "Update fish history"
    minute: "*/10"
    disabled: false
    job: "/bin/sh {{ ansible_env.HOME }}/.scripts/backup-fish-history.sh \
          2>> {{ ansible_env.HOME }}/backup-fish-history-error-logs.txt \
          1>> {{ ansible_env.HOME }}/gdrive-pessoal/pessoal/programação/cron-logs/stdout-logs/backup-fish-history-stdout-logs.txt"

- name: install cron job (update-inventory-ip)
  tags:
    - full-install
    - light-install
    - cron
    - fish
  ansible.builtin.cron:
    user: "{{ ansible_env.USER }}"
    name: "update vm inventory ip"
    special_time: reboot
    disabled: false
    job: "cd {{ ansible_env.HOME }}/eureciclo/datalake-infra/main-datalake-infra/ && /bin/sh ansible/update-inventory-ip.sh \
          2>> {{ ansible_env.HOME }}/update-inventory-ip-error-logs.txt \
          1>> {{ ansible_env.HOME }}/gdrive-pessoal/pessoal/programação/cron-logs/stdout-logs/update-inventory-ip-stdout-logs.txt"

- name: install cron job (push notes to git repository)
  tags:
    - full-install
    - light-install
    - cron
  ansible.builtin.cron:
    user: "{{ ansible_env.USER }}"
    name: "push notes to git repository"
    minute: "*/10"
    disabled: false
    job: "/bin/sh {{ ansible_env.HOME }}/.scripts/push-new-notes.sh \
          2>> {{ ansible_env.HOME }}/push-new-notes-error-logs.txt \
          1>> {{ ansible_env.HOME }}/gdrive-pessoal/pessoal/programação/cron-logs/stdout-logs/push-new-notes-stdout-logs.txt"

- name: install cron job (Auto adjust screen brightness)
  tags:
    - full-install
    - light-install
    - cron
    - auto-adjust-brightness
  ansible.builtin.cron:
    user: root
    name: "Auto adjust screen brightness"
    minute: "*/5"
    hour: "17-19,6-15"
    disabled: false
    job: "/bin/sh {{ ansible_env.HOME }}/.scripts/auto-adjust-brightness.sh \
          2>> {{ ansible_env.HOME }}/auto-adjust-brightness-error-logs.txt \
          1>> {{ ansible_env.HOME }}/gdrive-pessoal/pessoal/programação/cron-logs/stdout-logs/auto-adjust-brightness-stdout-logs.txt"
  become: true
