---
- name: Install doas package
  tags:
    - full-install
    - light-install
    - doas
  ansible.builtin.package:
    name: doas
    state: present
    update_cache: false
  become: true

- name: copy file doas.conf to /etc
  tags:
    - full-install
    - light-install
    - doas
  ansible.builtin.copy:
    src: doas.conf
    dest: /etc
    owner: root
    group: root
    mode: 0644
  become: true

# Gotta learn to run ansible with doas before getting rid of sudo
# - name: uninstall sudo
#   tags:
#     - full-install
#     - light-install
#     - doas
# ansible.builtin.package:
#     name:
#       - sudo
#     state: absent
#     update_cache: no
#   become: true
