---
- name: Clone dwmstatus
  tags:
    - full-install
    - light-install
    - dwmblocks
  ansible.builtin.git:
    version: master
    repo: https://git.suckless.org/dwmstatus
    dest: "{{ lookup('env', 'HOME') }}/.config/dwmstatus"
  ignore_errors: true

- name: Install dwmstatus
  tags:
    - full-install
    - light-install
    - dwmblocks
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/.config/dwmstatus"
    target: install
  become: true
