---
- name: Set packages variables when distribution is Archlinux (if necessary)
  tags:
    - full-install
    - light-install
    - packages
  ansible.builtin.set_fact:
    xorg:
      - xorg-server
      - xorg-xinit
      - xorg-xsetroot
      - xorg-xrandr
      - xorg-setxkbmap
    rfkill: util-linux-libs
    python_pip: python-pip
    base_devel: base-devel
    wpa_supplicant: wpa_supplicant
    liberation_font: ttf-liberation
    postgres: postgresql-libs
    fd: fd
  when: ansible_distribution == "Archlinux"

- name: Set packages variable when distribution is Ubuntu (if necessary)
  tags:
    - full-install
    - light-install
    - packages
  ansible.builtin.set_fact:
    xorg:
      - xorg
      - libxrandr2
      - libxrandr-dev
      - xorg
      - xorg
    rfkill: rfkill
    python_pip: pipenv
    base_devel: make
    wpa_supplicant: wpasupplicant
    liberation_font: fonts-liberation
    postgres: postgresql
    fd: fd-find
  when: ansible_distribution == "Ubuntu"

- name: install packages and update cache
  tags:
    - full-install
    - light-install
    - packages
  ansible.builtin.package:
    name:
      - tmux
      - tmuxp
      - "{{ xorg[0] }}"
      - "{{ xorg[1] }}"
      - "{{ xorg[2] }}"
      - "{{ xorg[3] }}"
      - "{{ xorg[4] }}"
      - xautolock
      - xbindkeys
      - arandr
      - numlockx
      - "{{ python_pip }}"
      - feh
      - unclutter
      - "{{ base_devel }}"
      - xclip
      - brightnessctl
      - "{{ wpa_supplicant }}"
      - ripgrep
      - "{{ fd }}"
      - fzf
      - lxsession
      - flameshot
      - bat
      - dunst
      - qt5ct # To set theme for qt applications
      - "{{ rfkill }}"
      - csvkit
      - yamllint
      - ansible-lint
      - npm # Necessary to install gramarly language server in neovim play
      - qutebrowser
      - unzip
      - "{{ liberation_font }}"
      - "{{ postgres }}"
    state: present
    update_cache: true
  become: true

- name: install packages that i still have not set in ubuntu
  tags:
    - full-install
    - light-install
    - packages
  ansible.builtin.package:
    name:
      - pamixer # missing ubuntu
      - ttf-nerd-fonts-symbols-2048-em-mono # missing ubuntu
      - ttf-joypixels # missing ubuntu
      - ttf-linux-libertine # missing ubuntu
      - arc-gtk-theme # missing ubuntu
      - clipmenu # missing ubuntu
      - noto-fonts-emoji # missing ubuntu
      - xcompmgr # Compositor to have transparency on the terminal
      - bleachbit # Utility to free space on disk
      - aws-cli-v2
    state: present
    update_cache: true
  become: true
  when: ansible_distribution == "Archlinux"
