---
- name: install rsync package
  tags:
    - full-install
    - light-install
    - rsync
  ansible.builtin.package:
    name:
      - rsync
    state: present
    update_cache: true
  become: true

- name: Ensure hd-interno directory exists.
  tags:
    - full-install
    - light-install
    - rsync
  ansible.builtin.file:
    dest: "/mnt/hd-interno/"
    mode: 0755
    state: directory
  become: true

- name: Ensure hd-externo directory exists.
  tags:
    - full-install
    - light-install
    - rsync
  ansible.builtin.file:
    dest: "/mnt/hd-externo/"
    mode: 0755
    state: directory
  become: true

- name: Make sure rsync can run without root privileges
  tags:
    - full-install
    - light-install
    - rsync
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/frank
    state: present
    regexp: "{{ ansible_env.USER }} ALL = NOPASSWD: /usr/bin/rsync"
    line: last
  become: true

- name: install cron job (Backup home directory with rsync to internal hard drive)
  tags:
    - full-install
    - light-install
    - rsync
  ansible.builtin.cron:
    user: "{{ ansible_env.USER }}"
    name: "backup home directory to internal drive"
    minute: "0"
    hour: "8,21"
    weekday: "SAT"
    disabled: false
    job: "{{ ansible_env.HOME }}/.scripts/backup-to-internal-hard-drive.sh \
          2>> {{ ansible_env.HOME }}/gdrive-pessoal/pessoal/programação/cron-logs/error-logs/backup-internal-hard-drive-error-logs.txt \
          1>> {{ ansible_env.HOME }}/gdrive-pessoal/pessoal/programação/cron-logs/stdout-logs/backup-internal-hard-drive-stdout-logs.txt"

- name: install cron job (Backup home directory with rsync to external hard drive)
  tags:
    - full-install
    - light-install
    - rsync
  ansible.builtin.cron:
    user: "{{ ansible_env.USER }}"
    name: "backup home directory to external drive"
    minute: "0"
    hour: "8,21"
    weekday: "SUN"
    disabled: false
    job: "{{ ansible_env.HOME }}/.scripts/backup-to-external-hard-drive.sh \
          2>> {{ ansible_env.HOME }}/gdrive-pessoal/pessoal/programação/cron-logs/error-logs/backup-external-hard-drive-error-logs.txt \
          1>> {{ ansible_env.HOME }}/gdrive-pessoal/pessoal/programação/cron-logs/stdout-logs/backup-external-hard-drive-stdout-logs.txt"
