---
- name: Clone st
  tags:
    - full-install
    - light-install
    - st
  ansible.builtin.git:
    version: main
    repo: git@github.com:andre-gonzalez/st.git
    dest: "{{ ansible_env.HOME }}/.config/st"
    accept_hostkey: true
  ignore_errors: true

- name: Install st
  tags:
    - full-install
    - light-install
    - st
  community.general.make:
    chdir: "{{ ansible_env.HOME }}/.config/st"
    target: install
  become: true
