---
- name: Extract anki files
  tags:
    - full-install
    - light-install
    - anki
  ansible.builtin.unarchive:
    src: "{{ lookup('env', 'HOME') }}/.config/anki/anki-installer.tar.zst"
    dest: "{{ lookup('env', 'HOME') }}/.config/anki/install-files"
  listen: proceed anki installation

- name: Install anki
  tags:
    - full-install
    - light-install
    - anki
  ansible.builtin.script:
    chdir: "{{ lookup('env', 'HOME') }}/.config/anki/install-files/{{ json_reponse.json.assets.2.name | regex_replace( '\\.\\w*\\.\\w*$', '')  }}"
    cmd: "{{ lookup('env', 'HOME') }}/.config/anki/install-files/{{ json_reponse.json.assets.2.name | regex_replace( '\\.\\w*\\.\\w*$', '')  }}/install.sh"
  become: true
  listen: proceed anki installation

- name: restart systemd-networkd
  tags:
    - full-install
    - light-install
    - network
  ansible.builtin.service:
    name: systemd-networkd
    state: restarted
    enabled: true
  become: true
  listen: "restart network"

- name: start iwd
  tags:
    - full-install
    - light-install
    - network
  ansible.builtin.service:
    name: iwd
    state: restarted
    enabled: true
  become: true
  listen: "restart network"

- name: restart libvirt
  tags:
    - full-install
    - light-install
    - libvirt
  ansible.builtin.service:
    name: libvirtd
    state: restarted
    enabled: true
  become: true
  listen: "finish libvirt configuration"

# - name: virsh start
#   tags:
#     - full-install
#     - light-install
#     - libvirt
#   ansible.builtin.command: virsh net-autostart default && virsh net-start default
#   become: true
#   listen: "finish libvirt configuration"

- name: Disable root login via ssh
  tags:
    - full-install
    - light-install
    - security
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    backup: true
  become: true
  listen: "secure ssh"

- name: Disable password login via ssh
  tags:
    - full-install
    - light-install
    - security
    - ssh
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
    backup: true
  become: true
  listen: "secure ssh"

- name: install denyhosts
  tags:
    - full-install
    - light-install
    - security
    - ssh
  ansible.builtin.package:
    name: denyhosts
  become: true
  listen: "secure ssh"

- name: restart ssh
  tags:
    - full-install
    - light-install
    - security
    - ssh
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true
  listen: "secure ssh"

- name: restart preload
  tags:
    - full-install
    - light-install
    - preload
  ansible.builtin.service:
    name: preload
    state: restarted
    enabled: true
  become: true

- name: restart tlp
  tags:
    - full-install
    - light-install
    - save-battery
    - tlp
  ansible.builtin.service:
    name: tlp
    state: restarted
    enabled: true
  become: true

- name: Calibrate powertop
  tags:
    - full-install
    - light-install
    - save-battery
    - powertop
  ansible.builtin.command: powertop --calibrate
  become: true

- name: Mark all informant news as read
  tags:
    - aur
    - light-install
    - packages
    - full-install
  ansible.builtin.command: informant read --all
  become: true
  ignore_errors: true

- name: set up dotfiles
  tags:
    - full-install
    - light-install
    - dotfiles
  ansible.builtin.command: "/usr/bin/git --git-dir={{ ansible_env.HOME }}/.config/dotfiles/ --work-tree={{ ansible_env.HOME }} checkout -f"

- name: restart pulseaudio
  tags:
    - full-install
    - light-install
    - pulseaudio
  ansible.builtin.service:
    name: pulseaudio
    state: restarted
    enabled: true
  become: true
  listen: "restart pulseaudio"

- name: Create samba password and the user {{ ansible_env.USER }}
  tags:
    - full-install
    - samba
  ansible.builtin.shell: "(echo '{{ samba_pass }}'; echo '{{ samba_pass }}') | smbpasswd -s -a {{ ansible_env.USER }}"
  register: smbpasswd
  changed_when: "'Added user' in smbpasswd.stdout"
  become: true
  listen: "finish samba configuration"

- name: start samba (smb) service
  tags:
    - full-install
    - samba
  ansible.builtin.service:
    name: smb
    state: restarted
    enabled: true
  become: true
  listen: "finish samba configuration"

- name: start samba (nmb) service
  tags:
    - full-install
    - samba
  ansible.builtin.service:
    name: nmb
    state: restarted
    enabled: true
  become: true
  listen: "finish samba configuration"
